<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 ./Cloth.glb
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	export const ref = new Group();

	const gltf = useGltf('/Cloth.glb');

	const component = forwardEventHandlers();

	import { useTexture } from '@threlte/extras';
	const cloth_baseColor = useTexture('/export/Untitled material_BaseColor.jpg');

	const cloth_normal = useTexture('/export/Untitled material_Normal.jpg');

	const cloth_roughnessMap = useTexture('/export/Untitled material_Roughness.jpg');

	const cloth_opacity = useTexture('/export/Untitled material_Opacity.jpg');

	const cloth_height = useTexture('/export/Untitled material_Height.jpg');

	// $: console.log($cloth_height); // eventually THREE.Texture
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<!-- <T.Mesh
			geometry={gltf.nodes.Cloth.geometry}
			material={gltf.materials['Material.001']}
			position={[0, 0.4, 0]}
			scale={0.01}
		/> -->
		<T.Mesh geometry={gltf.nodes.Cloth.geometry} position={[0, 0.4, 0]} scale={0.01}>
			<T.MeshStandardMaterial
				color={'#ffffff'}
				roughness={1}
				metalness={1}
				map={$cloth_baseColor}
				normalMap={$cloth_normal}
				roughnessMap={$cloth_roughnessMap}
				alphaMap={$cloth_opacity}
				transparent={true}
				displacementMap={$cloth_height}
				displacementScale={10}
			/>
		</T.Mesh>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
