<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 ./clothFolded.glb
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { useTexture } from '@threlte/extras';

	export const ref = new Group();

	const gltf = useGltf('/clothFolded.glb');

	const component = forwardEventHandlers();

	// --------------------------------------------------------Custom code
	const cloth_baseColor = useTexture('/clothFold/CF_BaseColor.jpg');
	const cloth_normal = useTexture('/clothFold/CF_Normal.jpg');
	const cloth_roughnessMap = useTexture('/clothFold/CF_Roughness.jpg');
	const cloth_opacity = useTexture('/clothFold/CF_Opacity.jpg');
	const cloth_height = useTexture('/clothFold/CF_Height.jpg');
	const cloth_AO = useTexture('/clothFold/CF_AmbientOcclusion.jpg');

	$: $gltf
		? addItem($gltf, $cloth_height, $cloth_opacity, $cloth_AO, $cloth_roughnessMap)
		: 'false';

	function addItem(item, height, opa, ao, rough) {
		// Settings
		item.materials.ClothF_M.transparent = false;
		item.materials.ClothF_M.alphaToCoverage = true;
		item.materials.ClothF_M.blendEquation = 0;
		item.materials.ClothF_M.dithering = true;
		item.materials.ClothF_M.side = 2;
		item.materials.ClothF_M._alphaTest = 1;

		item.materials.ClothF_M.displacementMap = height;
		item.materials.ClothF_M.aoMap = ao;
		// item.materials.ClothF_M.alphaMap = opa;
		item.materials.ClothF_M.roughnessMap = rough;

		item.materials.ClothF_M.normalScale.x = 2.5;
		item.materials.ClothF_M.normalScale.y = -2.5;
		item.materials.ClothF_M.aoMapIntensity = 1.5;
		item.materials.ClothF_M.displacementScale = 0.01;

		console.log($gltf);
	}

	// --------------------------------------------------------Custom code
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh geometry={gltf.nodes.Plane005.geometry} material={gltf.materials.ClothF_M} />
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
