<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 .\static\GLTF\DrawCord_glb + textures\Draw cord_V2.gltf
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useTexture } from '@threlte/extras';

	export const ref = new Group();

	const gltf = useGltf('/GLTF/DrawCord_glb_textures/Draw cord_V2.gltf');

	const component = forwardEventHandlers();

	// --------------------------------------------------------Custom code
	const _baseColor = useTexture('/GLTF/DrawCord_glb_textures/1k/Substance_graph_basecolor.jpg');
	const _ambientocclusion = useTexture(
		'/GLTF/DrawCord_glb_textures/1k/Substance_graph_ambientocclusion.jpg'
	);
	const _normal = useTexture('/GLTF/DrawCord_glb_textures/1k/Substance_graph_normal.jpg');
	const _roughness = useTexture('/GLTF/DrawCord_glb_textures/1k/Substance_graph_roughness.jpg');

	$: if ($gltf) {
		console.log($gltf);
		addItem($gltf, $_ambientocclusion, $_baseColor, $_normal, $_roughness);
	} else console.log('Not Loaded yet!');

	function addItem(item, ao, base, normal, rough) {
		// Settings
		item.materials.Pattern_Mat.transparent = false;
		item.materials.Pattern_Mat.alphaToCoverage = true;
		item.materials.Pattern_Mat.blendEquation = 0;
		item.materials.Pattern_Mat.dithering = true;
		item.materials.Pattern_Mat.side = 2;
		item.materials.Pattern_Mat._alphaTest = 1;

		// item.materials.Pattern_Mat.displacementMap = height;
		item.materials.Pattern_Mat.aoMap = ao;
		// item.materials.Pattern_Mat.alphaMap = opa;
		item.materials.Pattern_Mat.roughnessMap = rough;

		item.materials.Pattern_Mat.normalScale.x = 10;
		item.materials.Pattern_Mat.normalScale.y = -10;
		item.materials.Pattern_Mat.aoMapIntensity = 1;
		item.materials.Pattern_Mat.displacementScale = 0.01;

		console.log($gltf);
	}
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh geometry={gltf.nodes.DrawCordBody.geometry} material={gltf.materials.Pattern_Mat} />
		<T.Mesh geometry={gltf.nodes.Cylinder002.geometry} material={gltf.materials.WhitePlastic_Mat} />
		<T.Mesh
			geometry={gltf.nodes.Cylinder002_1.geometry}
			material={gltf.materials.BlackPlastic_Mat}
		/>
		<T.Mesh geometry={gltf.nodes.Cylinder001.geometry} material={gltf.materials.WhitePlastic_Mat} />
		<T.Mesh
			geometry={gltf.nodes.Cylinder001_1.geometry}
			material={gltf.materials.BlackPlastic_Mat}
		/>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
