<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 ./Sphere_UV.glb
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useTexture } from '@threlte/extras';
	import { writable } from 'svelte/store';
	import * as THREE from 'three';
	export const ref = new Group();

	const gltf = useGltf('/Sphere_UV.glb');

	const component = forwardEventHandlers();

	// --------------------------------------------------------Custom code
	const cloth_baseColor = useTexture('/export/Untitled material_BaseColor.jpg');

	// cloth_baseColor.wrapS = THREE.RepeatWrapping;
	// cloth_baseColor.wrapT = THREE.RepeatWrapping;
	// cloth_baseColor.repeat.set(2, 2);
	const cloth_normal = useTexture('/export/Untitled material_Normal.jpg');
	const cloth_roughnessMap = useTexture('/export/Untitled material_Roughness.jpg');
	const cloth_opacity = useTexture('/export/Untitled material_Opacity.jpg');
	const cloth_height = useTexture('/export/Untitled material_Height.jpg');

	$: $cloth_height ? console.log($cloth_height) : 'false';

	$: $gltf ? addItem() : 'false';

	function addItem() {
		repeatTexture($cloth_baseColor);
		repeatTexture($cloth_normal);
		repeatTexture($cloth_roughnessMap);
		repeatTexture($cloth_opacity);
		repeatTexture($cloth_height);
	}

	function repeatTexture(item) {
		item.wrapS = THREE.RepeatWrapping;
		item.wrapT = THREE.RepeatWrapping;
		item.repeat.set(50, 50);
	}

	// --------------------------------------------------------Custom code
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<!-- <T.Mesh geometry={gltf.nodes.Sphere.geometry} material={gltf.materials.ClothM} /> -->
		<T.Mesh geometry={gltf.nodes.Sphere.geometry}>
			<T.MeshPhysicalMaterial
				color={'#ffffff'}
				roughness={1}
				metalness={1}
				map={$cloth_baseColor}
				normalMap={$cloth_normal}
				roughnessMap={$cloth_roughnessMap}
				alphaMap={$cloth_opacity}
				transparent={true}
				displacementMap={$cloth_height}
				displacementScale={0.01}
				wireframe={false}
			/>
		</T.Mesh>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
